global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [job]
        target_label: job
        replacement: 'cadvisor'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']